sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '7'
before_script:
- npm prune
script:
- npm run lint:js
- npm run lint:md
after_success:
- curl -Lo travis_after_all.py https://git.io/travis_after_all
- python travis_after_all.py
- export $(cat .to_export_back) &> /dev/null
deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy.sh
  on:
    all_branches: true
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_8be1d4350cb7_key -iv $encrypted_8be1d4350cb7_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- openssl aes-256-cbc -K $encrypted_ea8f0c217541_key -iv $encrypted_ea8f0c217541_iv
  -in .travis/travis_rsa.enc -out ~/.ssh/travis_rsa -d
- chmod 600 ~/.ssh/travis_rsa
- chmod 600 ~/.ssh/id_rsa
